// src/components/ProductForm/styles.ts
import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  card: {
    backgroundColor: "#f0ffe8",
    padding: "24px",
    borderRadius: "12px",
    width: "100%",
    maxWidth: "800px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
    fontFamily: "Arial, sans-serif",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
  },
  titleInput: {
    width: "100%",
    backgroundColor: "#AEDCB8",
    border: "none",
    borderRadius: "6px",
    padding: "10px",
    fontSize: "16px",
    textAlign: "center",
    fontWeight: 600,
    marginBottom: "20px",
    outline: "none",
    color: "#333",
  },
  mainContent: {
    display: "flex",
    justifyContent: "space-between",
    gap: "30px",
    width: "100%",
  },
  columnLeft: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  columnRight: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  label: {
    fontWeight: "bold",
    fontSize: "14px",
    marginBottom: "8px",
    color: "#333",
    textAlign: "center",
    display: "block",
  },
  imagePreviewBox: {
    width: "100%",
    backgroundColor: "#90B498",
    borderRadius: "8px",
    height: "180px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
    color: "white",
    marginBottom: "20px",
    fontSize: "14px",
  },
  previewImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    position: "absolute",
  },
  textarea: {
    width: "100%",
    backgroundColor: "#AEDCB8",
    border: "none",
    borderRadius: "8px",
    padding: "12px",
    fontSize: "14px",
    outline: "none",
    resize: "none",
    height: "180px",
    marginBottom: "20px",
  },
  quantityWrapper: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    marginBottom: "20px",
    justifyContent: "center",
  },
  btnSmall: {
    width: "36px",
    height: "36px",
    backgroundColor: "#AEDCB8",
    border: "none",
    borderRadius: "6px",
    fontSize: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  quantityInput: {
    width: "70px",
    height: "36px",
    backgroundColor: "#AEDCB8",
    borderRadius: "6px",
    border: "none",
    textAlign: "center",
    fontSize: "15px",
    fontWeight: "bold",
    outline: "none",
    appearance: "textfield",
  },
  priceWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    width: "100%",
  },
  currencySymbol: {
    fontSize: "18px",
    fontWeight: "bold",
  },
  priceInput: {
    width: "100px",
    height: "36px",
    backgroundColor: "#AEDCB8",
    border: "none",
    borderRadius: "6px",
    textAlign: "center",
    fontSize: "15px",
    outline: "none",
  },
  specList: {
    paddingLeft: "0",
    listStyle: "none",
    marginBottom: "15px",
    width: "100%",
    fontSize: "14px",
  },
  specItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "4px 0",
    fontWeight: 500,
  },
  specBullet: {
    marginRight: "8px",
    fontWeight: "bold",
  },
  removeSpecBtn: {
    background: "transparent",
    border: "none",
    color: "#d9534f",
    fontSize: "14px",
    fontWeight: "bold",
    marginLeft: "8px",
    padding: "2px",
    cursor: "pointer",
  },
  addSpecBtn: {
    backgroundColor: "#AEDCB8",
    border: "none",
    borderRadius: "6px",
    padding: "10px 15px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    fontSize: "13px",
    width: "100%",
  },
  specInputWrapper: {
    display: "flex",
    gap: "8px",
    width: "100%",
  },
  specTextInput: {
    flex: 1,
    backgroundColor: "#fff",
    border: "2px solid #AEDCB8",
    borderRadius: "6px",
    padding: "6px 10px",
    fontSize: "13px",
    outline: "none",
  },
  specActionBtn: {
    width: "32px",
    height: "32px",
    border: "none",
    borderRadius: "6px",
    fontWeight: "bold",
    fontSize: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtn: {
    backgroundColor: "#90B498",
    color: "#000",
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    fontWeight: "bold",
    fontSize: "14px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    cursor: "pointer",
  },
};