// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104091752_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aankoop", b =>
                {
                    b.Property<int>("AankoopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AankoopId"));

                    b.Property<int>("AanKoopHoeveelheid")
                        .HasColumnType("integer");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBetaald")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("AankoopId");

                    b.ToTable("Aankoop");
                });

            modelBuilder.Entity("backend.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GebruikerId"));

                    b.Property<string>("Emailadres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Huisnummer")
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("Straat")
                        .HasColumnType("text");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("text");

                    b.HasKey("GebruikerId");

                    b.ToTable("gebruiker");
                });

            modelBuilder.Entity("backend.Models.ProductGegevens", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Fotos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("integer");

                    b.Property<string>("ProductBeschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductNaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerkoperId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("product_gegevens");
                });

            modelBuilder.Entity("backend.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestModels");
                });

            modelBuilder.Entity("backend.Models.Veiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Eindtijd")
                        .HasColumnType("integer");

                    b.Property<decimal>("Huidigeprijs")
                        .HasColumnType("numeric");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Startprijs")
                        .HasColumnType("numeric");

                    b.Property<int>("Starttijd")
                        .HasColumnType("integer");

                    b.Property<int>("VeilingMeesterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("veiling");
                });

            modelBuilder.Entity("backend.Models.VeilingMeester", b =>
                {
                    b.Property<int>("MeesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeesterId"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("integer");

                    b.HasKey("MeesterId");

                    b.ToTable("veiling_meester");
                });

            modelBuilder.Entity("backend.Models.Verkoper", b =>
                {
                    b.Property<int>("VerkoperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerkoperId"));

                    b.Property<string>("Adresgegevens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bedrijfsgegevens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinancieleGegevens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VerkoperId");

                    b.ToTable("verkoper");
                });
#pragma warning restore 612, 618
        }
    }
}
