// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107201824_LastMigrationHopefully")]
    partial class LastMigrationHopefully
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aankoop", b =>
                {
                    b.Property<int>("AankoopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AankoopId"));

                    b.Property<int>("AanKoopHoeveelheid")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBetaald")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("AankoopId");

                    b.HasIndex("ProductId");

                    b.ToTable("aankoop");
                });

            modelBuilder.Entity("backend.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GebruikerId"));

                    b.Property<string>("Emailadres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Huisnummer")
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Straat")
                        .HasColumnType("text");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("text");

                    b.HasKey("GebruikerId");

                    b.ToTable("gebruiker");
                });

            modelBuilder.Entity("backend.Models.Locatie", b =>
                {
                    b.Property<int>("LocatieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocatieId"));

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocatieNaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocatieId");

                    b.ToTable("locatie");
                });

            modelBuilder.Entity("backend.Models.ProductGegevens", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("EindPrijs")
                        .HasColumnType("numeric");

                    b.Property<string>("Fotos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("integer");

                    b.Property<decimal>("Huidigeprijs")
                        .HasColumnType("numeric");

                    b.Property<int>("LocatieId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductBeschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductNaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StartPrijs")
                        .HasColumnType("numeric");

                    b.Property<int>("VeilingId")
                        .HasColumnType("integer");

                    b.Property<int>("VerkoperId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("product_gegevens");
                });

            modelBuilder.Entity("backend.Models.ProductSpecificatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductGegevensProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecificatieId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductGegevensProductId");

                    b.ToTable("product_specificaties");
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("integer");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("backend.Models.Specificaties", b =>
                {
                    b.Property<int>("SpecificatieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecificatieId"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpecificatieId");

                    b.ToTable("specificaties");
                });

            modelBuilder.Entity("backend.Models.Veiling", b =>
                {
                    b.Property<int>("VeilingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VeilingId"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Eindtijd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocatieId")
                        .HasColumnType("integer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Starttijd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VeilingMeesterId")
                        .HasColumnType("integer");

                    b.HasKey("VeilingId");

                    b.ToTable("veiling");
                });

            modelBuilder.Entity("backend.Models.VeilingMeester", b =>
                {
                    b.Property<int>("MeesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeesterId"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("integer");

                    b.HasKey("MeesterId");

                    b.ToTable("veiling_meester");
                });

            modelBuilder.Entity("backend.Models.Verkoper", b =>
                {
                    b.Property<int>("VerkoperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerkoperId"));

                    b.Property<string>("Adresgegevens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bedrijfsgegevens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinancieleGegevens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GebruikerId")
                        .HasColumnType("integer");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VerkoperId");

                    b.ToTable("verkoper");
                });

            modelBuilder.Entity("backend.Models.Aankoop", b =>
                {
                    b.HasOne("backend.Models.ProductGegevens", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.ProductSpecificatie", b =>
                {
                    b.HasOne("backend.Models.ProductGegevens", null)
                        .WithMany("ProductSpecificaties")
                        .HasForeignKey("ProductGegevensProductId");
                });

            modelBuilder.Entity("backend.Models.ProductGegevens", b =>
                {
                    b.Navigation("ProductSpecificaties");
                });
#pragma warning restore 612, 618
        }
    }
}
